export const libraryItems = [
  {
    id: '1',
    tag: 'PDF',
    date: '2025. 02. 01',
    title: 'Tamalpa Life/Art Process 소개 브로셔',
    subtitle: 'Introduction Brochure',
    desc: '한국어로 번역된 타말파 Life/Art Process 공식 소개 자료입니다. 프로그램의 철학과 구조를 한눈에 파악할 수 있습니다.',
    action: 'Download',
    content: [
      '이 브로셔는 미국 Tamalpa Institute의 공식 소개 자료를 한국어로 번역한 것입니다. Tamalpa Life/Art Process의 핵심 철학과 방법론, 교육 과정의 구조와 목표를 체계적으로 정리하여 처음 접하는 분들도 쉽게 이해할 수 있도록 구성하였습니다.',
      '브로셔에는 Life/Art Process의 다섯 가지 핵심 요소(움직임, 이미지, 이야기, 의례, 퍼포먼스)에 대한 설명이 포함되어 있으며, 각 요소가 어떻게 통합되어 치유와 성장의 과정을 만들어내는지를 안내합니다.',
      '또한 Tamalpa Institute의 역사와 설립 배경, Anna Halprin과 Daria Halprin의 철학적 기여, 전 세계 파트너 기관과의 협력 관계에 대한 정보도 담겨 있습니다.',
      '이 자료는 Tamalpa 트레이닝 프로그램에 관심 있는 분, 표현예술치료를 공부하는 학생, 관련 분야 전문가 모두에게 유용한 입문 자료입니다. 아래 버튼을 통해 PDF 파일을 다운로드하실 수 있습니다.',
    ],
    fileInfo: 'PDF · 한국어 · 16페이지 · 2.3MB',
  },
  {
    id: '2',
    tag: '영상',
    date: '2025. 01. 10',
    title: 'Anna Halprin — 표현예술치료의 창시자',
    subtitle: 'Founder of Expressive Arts Therapy',
    desc: '안나 할프린의 삶과 예술, 치유 작업을 담은 다큐멘터리 자료 모음입니다. 타말파 철학의 뿌리를 직접 만나볼 수 있습니다.',
    action: 'Watch',
    content: [
      'Anna Halprin의 예술적 여정과 치유 작업을 담은 다큐멘터리 및 인터뷰 영상 모음입니다. 100년이 넘는 삶을 통해 예술과 치유, 공동체와 자연의 연결을 탐구해온 그녀의 이야기를 직접 목소리로 들을 수 있습니다.',
      '수록된 영상 목록: 1) "Returning Home" — Anna Halprin의 자전적 다큐멘터리 (2002, 58분), 2) "Anna Halprin: Breath Made Visible" — 감독 Ruedi Gerber의 다큐멘터리 (2009, 80분), 3) Planetary Dance 아카이브 영상 (1981–2019), 4) Tamalpa Institute 레지던시 워크숍 발췌 영상.',
      '"Breath Made Visible"은 Anna의 암 투병부터 Planetary Dance까지, 그녀의 예술적 삶 전체를 아우르는 필수적인 작품입니다. 이 다큐멘터리는 전 세계 영화제에서 상영되었으며, 표현예술치료를 이해하는 데 가장 중요한 영상 자료 중 하나로 꼽힙니다.',
      '각 영상에 대한 한국어 자막 또는 해설 자료가 함께 제공됩니다. 영상 시청을 위해서는 회원 로그인 후 접근하실 수 있으며, 교육 목적으로만 활용해 주시기 바랍니다.',
    ],
    fileInfo: '영상 모음 · 총 4편 · 한국어 자막 제공',
  },
  {
    id: '3',
    tag: '문서',
    date: '2024. 12. 01',
    title: 'Level 1 트레이닝 커리큘럼 안내',
    subtitle: 'Level 1 Training Curriculum',
    desc: 'Level 1 개인 구현 과정의 전체 커리큘럼과 일정, 수료 조건을 상세히 안내하는 공식 문서입니다.',
    action: 'Download',
    content: [
      'Level 1 — 개인 구현(Personal Embodiment) 과정은 Tamalpa Life/Art Process의 입문 과정으로, 참가자들이 자신의 몸과 내면의 지혜를 탐구하는 여정입니다. 이 문서는 과정의 전체 구조와 내용을 안내합니다.',
      '과정 구성: Level 1은 총 9개월 과정으로, 매월 2박 3일 집중 워크숍(9회)과 온라인 통합 세션(월 1회)으로 구성됩니다. 소그룹(최대 15인)으로 진행되며, 개인 작업과 그룹 작업이 균형 있게 이루어집니다.',
      '핵심 모듈: 1) 신체 인식과 동작 탐구 — 몸의 감각을 깨우고 자연스러운 움직임 언어를 개발합니다. 2) 이미지와 상상력 — 내면의 이미지를 예술적 표현으로 연결합니다. 3) 개인 이야기 — 자신의 삶의 이야기를 예술적 형식으로 탐구합니다. 4) 의례와 공동체 — 그룹 작업을 통해 연결과 지지를 경험합니다. 5) 통합 퍼포먼스 — 과정을 마무리하는 개인 표현 작업.',
      '수료 조건: 전체 세션의 80% 이상 참여, 개인 일지 작성, 수료 발표 참여. 수료 후 Tamalpa Institute 공인 Level 1 수료증이 발급되며, Level 2 지도자 과정 지원 자격이 주어집니다.',
      '이 문서는 PDF 형식으로 제공되며, 커리큘럼 세부 내용, 강사 소개, 수료생 사례, 자주 묻는 질문이 포함되어 있습니다. 입학 상담을 원하시는 분은 문의하기 페이지를 통해 연락 주시기 바랍니다.',
    ],
    fileInfo: 'PDF · 한국어 · 24페이지 · 1.8MB',
  },
]
